### ISSUE TITLE
Not able to set height as 100% of View tag inside SyncedScrollView tag 

### ISSUE THREAD

**Issue by Sanath91009** [maxdietel/react-native-synced-scroll-views#1]
In the app.tsx file if I change the height as 100% for the Content tag then I am not able to see the Views in the Content tag.
Basically I want to give total space inside SyncedScrollView for View tag but I am not able to achieve this by {height:"100%"}
How can I acheive this ?

**Comment by maxdietel** [comment]
I am pretty sure this has nothing to do with the SyncedScrollView. Pls try to replace the SyncedScrollView with a normal ScrollView and see if it works.

**Comment by Sanath91009** [comment]
Yes for ScrollView also it is not working
Do you have any idea on how to make it work ? 

UPD: got it. Thanks

**Comment by maxdietel** [comment]
Just to clarify: Since it's a ScrollView the height of it is virtually infinite. Thats why height 100% on Children of the ScrollView doesn't work. This has nothing to do with the SyncedScrollView Component. A possibility is to get the Screen height and set the children height as the screen height.
